// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxtxfgvmzvorwrisxcay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94dHhmZ3ZtenZvcndyaXN4Y2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MTExNDIsImV4cCI6MjA3Nzk4NzE0Mn0.WEuj7toCwil5K329PuhT-P6xXJSxqU1eO0xZ80jTyUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});